export const zhCN = {
  appName: '学刻',
  nav: { focus: '专注台', tasks: '任务', today: '今日', settings: '设置' },
  timer: { start: '开始', pause: '暂停', resume: '继续', skip: '跳过', mini: '悬浮小窗', expand: '展开主窗口', noTask: '未绑定任务', cycleProgress: '本轮已完成 {completed} / {interval} 次专注', ready: '准备好后开始这一段专注。', paused: '计时已暂停。', running: '保持专注，稳步推进。', currentTask: '当前任务：{title}' },
  rest: { shortTitle: '短休时间', longTitle: '长休时间', shortHint: '离开屏幕、活动一下肩颈，稍后再继续。', longHint: '让大脑真正放松一会儿，再回来继续推进。', paused: '休息已暂停。', skip: '跳过并开始专注', continue: '继续休息', soundTitle: '本次休息声音', soundHint: '只影响当前这一次休息', quiet: '安静', music: '背景音乐' },
  task: { create: '新建任务', editTask: '编辑任务', editorHint: '任务用于标记每段专注时间的具体去向。', subtitle: '选择接下来要推进的事情，让每一段专注都有明确归属。', active: '进行中的任务', completedSection: '已完成任务（{count}）', currentFocus: '当前专注任务', currentEmpty: '还没有选择任务', currentHint: '你也可以不绑定任务直接专注，之后的统计会归入“未绑定任务”。', startFocus: '开始专注', viewFocus: '查看专注', setCurrent: '设为当前', current: '当前任务', complete: '完成', restore: '恢复', delete: '删除', deleteConfirmTitle: '删除这个任务？', deleteConfirmBody: '“{title}”会从任务列表中移除，已经完成的专注记录仍会保留任务名称。', confirmDelete: '确认删除', createFirst: '创建第一个任务', edit: '编辑', unbind: '取消当前任务', title: '任务名称', note: '备注（可选）', save: '保存', cancel: '取消', empty: '当前没有进行中的任务。' },
  today: { completed: '完成番茄', minutes: '专注分钟', focusDuration: '有效专注', pomodoroUnit: '个番茄', minuteUnit: '分钟', subtitle: '今天的专注成果', distribution: '时间分布', records: '专注记录', emptyTitle: '今天还没有完成专注', empty: '选择一个任务并完成第一段专注后，这里会生成你的今日记录。', chooseTask: '选择任务', summary: '{count} 个番茄 · {minutes} 分钟' },
  settings: { title: '设置', presetsTab: '方案库', timerTab: '计时与提醒', timerHeading: '安排你的专注节奏', timerHint: '计时参数会在下一阶段生效，当前正在进行的倒计时不会被打断。', durationGroup: '时间与循环', reminderGroup: '提醒与休息', notificationHint: '切换阶段时显示系统通知', soundHint: '阶段结束时播放清脆提示音', restSoundHint: '仅在短休和长休期间生效', createPreset: '保存为新方案', focus: '专注时长（分钟）', shortBreak: '短休时长（分钟）', longBreak: '长休时长（分钟）', interval: '长休间隔（完成番茄数）', notification: '阶段结束时通知', sound: '阶段结束时提示音', restSound: '休息期间声音', quiet: '安静', music: '背景音乐', save: '保存设置', presets: '专注方案', presetsHint: '选择一个方案即可同时设置专注和休息节奏；之后仍可按你的习惯调整。', builtin: '内置方案', mine: '我的方案', apply: '应用', current: '当前使用', savePreset: '保存当前设置为方案', updatePreset: '更新方案', presetName: '方案名称', cancelEdit: '取消编辑', edit: '编辑', delete: '删除', noPresets: '还没有自定义方案。', presetSummary: '每次专注 {focus} 分钟 · 短休 {shortBreak} 分钟 · 长休 {longBreak} 分钟 · 每完成 {interval} 次专注后长休', deepWork: '深度开发 / AI 项目', development: '日常开发', learning: '课程学习 / 跟练', writing: '写作与整理', errands: '碎片事务', lowEnergy: '低精力启动' },
  feedback: { timerUpdated: '计时状态已更新。', taskCreated: '任务已创建。', taskUpdated: '任务已更新。', taskDeleted: '任务已删除。', currentTaskSet: '已设为当前任务。', currentTaskCleared: '已取消当前任务。', settingsSaved: '设置已保存。', presetApplied: '方案已应用到当前设置。', presetCreated: '自定义方案已保存。', presetUpdated: '自定义方案已更新。', presetDeleted: '自定义方案已删除。' },
} as const
