export const IpcChannels = {
  getState: 'xueke:getState',
  timerStart: 'xueke:timer:start',
  timerPause: 'xueke:timer:pause',
  timerResume: 'xueke:timer:resume',
  timerSkip: 'xueke:timer:skip',
  windowShowMini: 'xueke:window:showMini',
  windowShowMain: 'xueke:window:showMain',
  mediaRestMusicUrl: 'xueke:media:restMusicUrl',
  tasksList: 'xueke:tasks:list',
  tasksCreate: 'xueke:tasks:create',
  tasksUpdate: 'xueke:tasks:update',
  tasksDelete: 'xueke:tasks:delete',
  tasksSetCurrent: 'xueke:tasks:setCurrent',
  settingsGet: 'xueke:settings:get',
  settingsUpdate: 'xueke:settings:update',
  focusPresetsList: 'xueke:focusPresets:list',
  focusPresetsCreate: 'xueke:focusPresets:create',
  focusPresetsUpdate: 'xueke:focusPresets:update',
  focusPresetsDelete: 'xueke:focusPresets:delete',
  statsToday: 'xueke:stats:today',
  timerTick: 'xueke:timer:tick',
  timerPhaseEnded: 'xueke:timer:phaseEnded',
  completionSound: 'xueke:completion:sound',
  dataChanged: 'xueke:data:changed',
  storeError: 'xueke:store:error',
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
