import React, { useEffect, useState } from 'react'
import type { DailyStats, Settings, Task, TimerSnapshot } from '../shared/types'
import { t } from './i18n'
import { formatMs } from './features/focus/formatMs'

type Page = 'focus' | 'tasks' | 'today' | 'settings'
const labels: Record<Page, string> = t.nav

export default function App(): React.JSX.Element {
  const [page, setPage] = useState<Page>('focus'); const [timer, setTimer] = useState<TimerSnapshot>(); const [tasks, setTasks] = useState<Task[]>([]); const [settings, setSettings] = useState<Settings>(); const [stats, setStats] = useState<DailyStats>(); const [currentTaskId, setCurrentTaskId] = useState<string>(); const [error, setError] = useState('')
  const refresh = async () => { try { const [state, nextTasks, nextSettings, nextStats] = await Promise.all([window.xueke.getState(), window.xueke.tasks.list(), window.xueke.settings.get(), window.xueke.stats.today()]); setTimer(state.timer); setCurrentTaskId(state.currentTaskId); setTasks(nextTasks); setSettings(nextSettings); setStats(nextStats) } catch (e) { setError(e instanceof Error ? e.message : '读取数据失败') } }
  useEffect(() => { void refresh(); const offTick = window.xueke.onTimerTick((value) => setTimer(value)); const offError = window.xueke.onStoreError((value) => setError(value.message)); return () => { offTick(); offError() } }, [])
  const invoke = async (action: () => Promise<unknown>) => { try { await action(); await refresh() } catch (e) { setError(e instanceof Error ? e.message : '操作失败') } }
  const task = tasks.find((item) => item.id === currentTaskId)
  return <main className="app-shell"><aside><div className="brand">{t.appName}</div><nav aria-label="主导航">{(Object.keys(labels) as Page[]).map((key) => <button className={page === key ? 'active' : ''} key={key} onClick={() => setPage(key)} type="button">{labels[key]}</button>)}</nav></aside><section className="content">{error && <p className="error">{error}<button onClick={() => void refresh()}>重试</button><button onClick={() => setError('')}>×</button></p>}{page === 'focus' && timer && <Focus timer={timer} task={task} longBreakInterval={settings?.longBreakInterval ?? 4} invoke={invoke} />}{page === 'tasks' && <Tasks tasks={tasks} currentTaskId={currentTaskId} invoke={invoke} />}{page === 'today' && <Today stats={stats} />}{page === 'settings' && settings && <SettingsPage settings={settings} invoke={invoke} />}</section></main>
}

function Focus({ timer, task, longBreakInterval, invoke }: { timer: TimerSnapshot; task?: Task; longBreakInterval: number; invoke: (fn: () => Promise<unknown>) => Promise<void> }) { const phase = { focus: '专注', shortBreak: '短休', longBreak: '长休' }[timer.phase]; const progress = t.timer.cycleProgress.replace('{completed}', String(timer.completedFocusCountInCycle)).replace('{interval}', String(longBreakInterval)); const taskLabel = task ? t.timer.currentTask.replace('{title}', task.title) : t.timer.noTask; const message = timer.status === 'idle' ? t.timer.ready : timer.status === 'paused' ? t.timer.paused : t.timer.running; return <><p className="eyebrow">{taskLabel} · {progress}</p><h1>{phase}</h1><div className="timer-card"><span>{phase}</span><strong>{formatMs(timer.remainingMs)}</strong><p>{message}</p><div className="actions">{timer.status === 'idle' && <button onClick={() => void invoke(() => window.xueke.timer.start())}>{t.timer.start}{phase}</button>}{timer.status === 'running' && <button onClick={() => void invoke(() => window.xueke.timer.pause())}>{t.timer.pause}</button>}{timer.status === 'paused' && <button onClick={() => void invoke(() => window.xueke.timer.resume())}>{t.timer.resume}</button>}{timer.status !== 'idle' && <button className="secondary" onClick={() => void invoke(() => window.xueke.timer.skip())}>{t.timer.skip}</button>}</div></div></> }
function Tasks({ tasks, currentTaskId, invoke }: { tasks: Task[]; currentTaskId?: string; invoke: (fn: () => Promise<unknown>) => Promise<void> }) {
  const [title, setTitle] = useState(''); const [note, setNote] = useState(''); const [editing, setEditing] = useState<Task>()
  const reset = () => { setTitle(''); setNote(''); setEditing(undefined) }
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!title.trim()) return; void invoke(async () => { if (editing) await window.xueke.tasks.update(editing.id, { title, note }); else await window.xueke.tasks.create({ title, note }); reset() }) }
  const startEdit = (task: Task) => { setEditing(task); setTitle(task.title); setNote(task.note ?? '') }
  return <><h1>{t.nav.tasks}</h1><form className="task-editor" onSubmit={submit}><label>{t.task.title}<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder="例如：完成英语阅读" /></label><label>{t.task.note}<textarea value={note} onChange={(e) => setNote(e.target.value)} rows={2} /></label><div className="actions"><button>{editing ? t.task.save : t.task.create}</button>{editing && <button className="secondary" onClick={reset} type="button">{t.task.cancel}</button>}</div></form>{currentTaskId && <button className="unbind" onClick={() => void invoke(() => window.xueke.tasks.setCurrent())}>{t.task.unbind}</button>}<div className="list">{tasks.length === 0 && <p>{t.task.empty}</p>}{tasks.map((task) => <article className="task" key={task.id}><div><b>{task.title}</b>{task.note && <small>{task.note}</small>}<small>{task.status === 'completed' ? '已完成' : '进行中'}</small></div><div className="row"><button className={task.id === currentTaskId ? 'selected' : ''} onClick={() => void invoke(() => window.xueke.tasks.setCurrent(task.id))}>{task.id === currentTaskId ? '当前任务' : '设为当前'}</button><button onClick={() => startEdit(task)}>{t.task.edit}</button><button onClick={() => void invoke(() => window.xueke.tasks.update(task.id, { status: task.status === 'active' ? 'completed' : 'active' }))}>{task.status === 'active' ? '完成' : '恢复'}</button><button className="danger" onClick={() => void invoke(() => window.xueke.tasks.delete(task.id))}>删除</button></div></article>)}</div></>
}
function Today({ stats }: { stats?: DailyStats }) { return <><h1>{t.nav.today}</h1><div className="stats"><div><b>{stats?.completedFocusCount ?? 0}</b><span>{t.today.completed}</span></div><div><b>{Math.round((stats?.focusMs ?? 0) / 60_000)}</b><span>{t.today.minutes}</span></div></div><div className="list">{stats?.byTask.length ? stats.byTask.map((item) => <article className="task" key={item.taskId ?? 'none'}><b>{item.title}</b><span>{t.today.summary.replace('{count}', String(item.completedFocusCount)).replace('{minutes}', String(Math.round(item.focusMs / 60_000)))}</span></article>) : <p>{t.today.empty}</p>}</div></> }
function SettingsPage({ settings, invoke }: { settings: Settings; invoke: (fn: () => Promise<unknown>) => Promise<void> }) { const [form, setForm] = useState(settings); useEffect(() => setForm(settings), [settings]); const field = (key: keyof Settings, label: string) => <label>{label}<input type="number" min="1" value={form[key] as number} onChange={(e) => setForm({ ...form, [key]: Number(e.target.value) })} /></label>; return <><h1>{t.settings.title}</h1><form className="settings" onSubmit={(e) => { e.preventDefault(); void invoke(() => window.xueke.settings.update(form)) }}>{field('focusMinutes', t.settings.focus)}{field('shortBreakMinutes', t.settings.shortBreak)}{field('longBreakMinutes', t.settings.longBreak)}{field('longBreakInterval', t.settings.interval)}<label className="check"><input type="checkbox" checked={form.notificationEnabled} onChange={(e) => setForm({ ...form, notificationEnabled: e.target.checked })} />{t.settings.notification}</label><label className="check"><input type="checkbox" checked={form.soundEnabled} onChange={(e) => setForm({ ...form, soundEnabled: e.target.checked })} />{t.settings.sound}</label><button>{t.settings.save}</button></form></> }
